package main.java.createNewHire;// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.firefox.FirefoxDriver;

import java.util.HashMap;
import java.util.Map;

public class NewHire {
  private WebDriver driver;

  @Test
  public void setUp() {//web driver location
    System.setProperty("webdriver.chrome.driver","E:\\Dropbox\\Google Drive\\NAU Boot Camp\\Selenium Course\\selenium-java-3.141.59\\drivers\\chromedriver.exe"); //web driver location
    WebDriver driver = new ChromeDriver();
    //driver.manage().window().maximize(); // maximizes browser view
    driver.get("https://hr-testing.buffsci.org/");

//    js = (JavascriptExecutor) driver;
//    vars = new HashMap<String, Object>();
  }
//  @After
//  public void tearDown() {
//    driver.quit();
//  }
//  @Test
//  public void NewHireTest() {
//
//  }
}
