package main.java.createNewHire;
// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static main.java.createNewHire.Female.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.JavascriptExecutor;

import java.util.*;


public class NewHireScript {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    static Female obj = new Female();


    @Before
    public void setUp() {
        driver = new FirefoxDriver();
        System.setProperty("webdriver.chrome.driver","E:\\Dropbox\\Google Drive\\NAU Boot Camp\\Selenium Course\\selenium-java-3.141.59\\drivers\\geckodriver.exe"); //web driver location
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void untitled() {
        driver.get("https://hr-testing.buffsci.org/");
        driver.manage().window().setSize(new Dimension(922, 699));
        driver.findElement(By.cssSelector(".btn")).click(); //login
        driver.findElement(By.id("email")).click(); //email
        driver.findElement(By.id("email")).sendKeys("admin@staging-buffsci.org");
        driver.findElement(By.id("password")).sendKeys("admin123test");
        driver.findElement(By.cssSelector(".btn")).click(); //login to enter
        driver.findElement(By.cssSelector(".btn:nth-child(5)")).click();
//        {
//            WebElement element = driver.findElement(By.cssSelector(".col-sm-3:nth-child(1) > .form-control"));
//            Actions builder = new Actions(driver);
//            builder.moveToElement(element).clickAndHold().perform();
//        }
//        {
//            WebElement element = driver.findElement(By.cssSelector(".col-sm-3:nth-child(1) > .form-control"));
//            Actions builder = new Actions(driver);
//            builder.moveToElement(element).perform();
//        }
//        {
//            WebElement element = driver.findElement(By.cssSelector(".col-sm-3:nth-child(1) > .form-control"));
//            Actions builder = new Actions(driver);
//            builder.moveToElement(element).release().perform();
//        }
        driver.findElement(By.cssSelector(".col-sm-3:nth-child(1) > .form-control")).click();
        {
            WebElement dropdown = driver.findElement(By.cssSelector(".col-sm-3:nth-child(1) > .form-control"));
            dropdown.findElement(By.xpath("//option[. = 'Ms.']")).click();
            driver.findElement(new By.ByClassName("form-control"));
        }
        driver.findElement(By.cssSelector(".col-sm-3 > .form-control > option:nth-child(2)")).click();
        driver.findElement(By.cssSelector(".col-sm-4:nth-child(3) > .form-control")).click();
        driver.findElement(By.cssSelector(".col-sm-4:nth-child(3) > .form-control")).sendKeys(); //first name
        driver.findElement(By.cssSelector(".form-group:nth-child(5) > .form-control")).click();
        driver.findElement(By.cssSelector(".form-group:nth-child(5) > .form-control")).sendKeys("reku"); //last name
        driver.findElement(By.cssSelector("#newHireForm .form-group:nth-child(6) > .form-control")).click();
        {
            WebElement dropdown = driver.findElement(By.cssSelector("#newHireForm .form-group:nth-child(6) > .form-control"));
            dropdown.findElement(By.xpath("//option[. = 'Building Substitute (BuffSci 2)']")).click();
        }
        driver.findElement(By.cssSelector(".form-control:nth-child(2) > option:nth-child(11)")).click();
        driver.findElement(By.cssSelector("#newHireForm .form-group:nth-child(7) .form-control")).click();
        driver.findElement(By.cssSelector("#newHireForm .form-group:nth-child(7) .form-control")).sendKeys("khyjer32@gmail.com"); //email
        driver.findElement(By.cssSelector("#newHireForm .form-group:nth-child(8) .form-control")).click();
//        driver.findElement(By.cssSelector("#newHireForm .form-group:nth-child(8) .form-control")).sendKeys(generateRandomDigits(10));  //phone
        driver.findElement(By.cssSelector("#newHireModal___BV_modal_footer_ > .btn-primary")).click();
        driver.findElement(By.cssSelector(".fa-user")).click();
        driver.findElement(By.linkText("Logout")).click();
    }

    protected void salutation() {
        // salutation list
        List<String> salutation = new ArrayList<>();
        salutation.add("Ms.");
        salutation.add("Mrs.");
        salutation.add("Miss");
        salutation.add("Ms.");
        salutation.add("Dr.");
    }


}