package main.java.SearchingProjects; // Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class FBSearchLexusRX350Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver","E:\\Dropbox\\Google Drive\\NAU Boot Camp\\Selenium Course\\selenium-java-3.141.59\\drivers\\chromedriver.exe"); //web driver location
    driver = new ChromeDriver(); //create new "Chrome driver" variable
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void fBSearchLexusRX350() {
    driver.get("https://www.facebook.com/");
    driver.findElement(By.id("email")).sendKeys("mekjanhan@gmail.com");
    driver.findElement(By.id("pass")).sendKeys("Glyuk_rukov/ki");
    driver.findElement(By.id("pass")).click();
    driver.findElement(By.id("u_0_2")).click();
    {

      WebElement element = driver.findElement(By.cssSelector("#jsc_c_5k .l9j0dhe7"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector("#jsc_c_25 .l9j0dhe7")).click();
    driver.findElement(By.cssSelector(".a8c37x1j > .tv7at329")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".a8c37x1j > .tv7at329"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector(".a8c37x1j > .tv7at329")).sendKeys("Lexus rx350");
    driver.findElement(By.cssSelector(".a8c37x1j > .tv7at329")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector(".buofh1pr > .q66pz984")).click();
    driver.findElement(By.id("jsc_c_9l")).click();
    driver.findElement(By.id("jsc_c_9l")).click();
    driver.findElement(By.id("jsc_c_9l")).click();
    driver.findElement(By.cssSelector("#jsc_c_b8 .muag1w35")).click();
    driver.findElement(By.id("jsc_c_9n")).click();
    driver.findElement(By.cssSelector(".oajrlxb2:nth-child(5) .oi732d6d")).click();
    driver.findElement(By.cssSelector(".dati1w0a .oajrlxb2 .oi732d6d")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".b3onmgus:nth-child(5) .aahdfvyu:nth-child(5) > .kr520xx4"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".oajrlxb2:nth-child(1) .q9uorilb > .hu5pjgll")).click();
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.cssSelector(".tojvnm2t:nth-child(1) > .jq4qci2q > .oajrlxb2")).click();
    driver.findElement(By.cssSelector(".\\_5f0v")).sendKeys("$2,000");
    driver.findElement(By.cssSelector(".tojvnm2t:nth-child(3) > .jq4qci2q > .oajrlxb2")).click();
    driver.findElement(By.cssSelector(".tojvnm2t:nth-child(3) > .jq4qci2q > .oajrlxb2")).click();
    driver.findElement(By.cssSelector(".tojvnm2t:nth-child(3) > .jq4qci2q > .oajrlxb2")).sendKeys("$7,000");
    js.executeScript("window.scrollTo(0,0)");
    {
      WebElement element = driver.findElement(By.cssSelector(".l9j0dhe7:nth-child(1) > .bq4bzpyk:nth-child(1) > .b3onmgus:nth-child(2) .rq0escxv:nth-child(2) .kr520xx4:nth-child(1)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
  }
}
