package main.java.SearchingProjects;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class LaptopI79thGen15inDedGraphicCheapFirstTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver","E:\\Dropbox\\Google Drive\\NAU Boot Camp\\Selenium Course\\selenium-java-3.141.59\\drivers\\chromedriver.exe"); //web driver location
    driver = new ChromeDriver(); //create new "Chrome driver" variable
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void LaptopI79thGen15inDedGraphicCheapFirstTest() {
    driver.get("https://www.ebay.com/");

    {
      WebElement element = driver.findElement(By.linkText("Electronics"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.id("gh-ac")).click();
    driver.findElement(By.id("gh-ac")).sendKeys("laptop");
    driver.findElement(By.id("gh-ac")).sendKeys(Keys.ENTER);
    {
      WebElement element = driver.findElement(By.id("gh-btn"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    js.executeScript("window.scrollTo(0,306)");
    driver.findElement(By.cssSelector("#x-refine__group__3 .x-refine__main__list--value:nth-child(1) .x-refine__select__svg > .cbx")).click();
    js.executeScript("window.scrollTo(0,21)");
    driver.findElement(By.cssSelector("#x-refine__group_1__2 .x-refine__main__list--value:nth-child(4) .x-refine__select__svg > .cbx")).click();
    js.executeScript("window.scrollTo(0,306)");
    js.executeScript("window.scrollTo(0,612)");
    driver.findElement(By.cssSelector("#x-refine__group_1__4 .x-refine__main__list--value:nth-child(8) .x-refine__select__svg > .cbx")).click();
    js.executeScript("window.scrollTo(0,48)");
    js.executeScript("window.scrollTo(0,714)");
    driver.findElement(By.cssSelector("#x-refine__group__5 .x-refine__main__list--value:nth-child(4) .rbx .rbx")).click();
    driver.findElement(By.cssSelector("#s0-13-11-5-1\\[1\\]-42-0 .expand-btn__cell")).click();
    driver.findElement(By.cssSelector("#s0-13-11-5-1\\[1\\]-42-0-content-menu > .fake-menu-button__item:nth-child(4) > span > span")).click();
    js.executeScript("window.scrollTo(0,102)");
    driver.findElement(By.cssSelector("#s0-13-11-0-1-2-6-2 > .fake-link")).click();
    driver.findElement(By.cssSelector("#c2-mainPanel-Graphics\\%20Processing\\%20Type > .x-overlay-aspect__label")).click();
    driver.findElement(By.id("c2-subPanel-Graphics%20Processing%20Type_Dedicated%20Graphics-0_cbx")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".x-overlay__wrapper--left"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".x-overlay__wrapper--left"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".x-overlay__wrapper--left"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector(".x-overlay-footer__apply-btn > span")).click();
  }
}
