package main.java.SearchingProjects;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

import org.junit.jupiter.api.BeforeEach;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Projcet1Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @BeforeEach
  public void setUp() {
    System.setProperty("webdriver.chrome.driver","E:\\Dropbox\\Google Drive\\NAU Boot Camp\\Selenium Course\\selenium-java-3.141.59\\drivers\\chromedriver.exe"); //web driver location
    driver = new ChromeDriver(); //create new "Chrome driver" variable
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  public String waitForWindow(int timeout) {
    try {
      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    Set<String> whNow = driver.getWindowHandles();
    Set<String> whThen = (Set<String>) vars.get("window_handles");
    if (whNow.size() > whThen.size()) {
      whNow.removeAll(whThen);
    }
    return whNow.iterator().next();
  }
  @Test
  public void projcet1() {
    driver.get("https://letskodeit.teachable.com/p/practice");
    driver.manage().window().setSize(new Dimension(1308, 771));
    driver.findElement(By.cssSelector(".block:nth-child(5)")).click();
    driver.findElement(By.id("bmwradio")).click();
    driver.findElement(By.id("carselect")).click();
    {
      WebElement dropdown = driver.findElement(By.id("carselect"));
      dropdown.findElement(By.xpath("//option[. = 'Benz']")).click();
    }
    driver.findElement(By.cssSelector("#carselect > option:nth-child(2)")).click();
    {
      WebElement dropdown = driver.findElement(By.id("multiple-select-example"));
      dropdown.findElement(By.xpath("//option[. = 'Apple']")).click();
    }
    driver.findElement(By.id("benzcheck")).click();
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.id("openwindow")).click();
    vars.put("win7213", waitForWindow(2000));
    vars.put("root", driver.getWindowHandle());
    driver.switchTo().window(vars.get("win7213").toString());
    vars.put("window_handles", driver.getWindowHandles());
    driver.switchTo().window(vars.get("root").toString());
    vars.put("win5624", waitForWindow(2000));
    driver.switchTo().window(vars.get("win5624").toString());
    driver.switchTo().window(vars.get("root").toString());
    driver.findElement(By.id("name")).click();
    driver.findElement(By.id("name")).sendKeys("Mike");
    driver.findElement(By.id("alertbtn")).click();
    assertThat(driver.switchTo().alert().getText(), is("Hello Mike, share this practice page and share your knowledge"));
    driver.findElement(By.id("name")).click();
    driver.findElement(By.id("name")).sendKeys("Meme");
    driver.findElement(By.id("confirmbtn")).click();
    assertThat(driver.switchTo().alert().getText(), is("Hello Meme, Are you sure you want to confirm?"));
    driver.switchTo().alert().accept();
    driver.findElement(By.id("product")).click();
    driver.findElement(By.id("displayed-text")).click();
    driver.findElement(By.id("displayed-text")).sendKeys("HideHsow");
    driver.findElement(By.id("show-textbox")).click();
    driver.findElement(By.linkText("Top")).click();
    driver.findElement(By.cssSelector(".block:nth-child(6)")).click();
  }
}
